import React from "react";
import { motion } from "framer-motion";
import { BarChart3, Database, TrendingUp, Eye } from "lucide-react";
import {
  SectionTitle,
  InfoCard,
  RolePill,
  FlowStepper,
  EmpathyMap,
  sectionVariants,
  itemVariants,
} from "@/components/ui";
import type { FlowItem } from "@/components/ui";
import RoleCard from "@/components/RoleCard";

// ===== 新的編號標題元件 =====
type SectionTitleNumberedProps = { title: string; number: string };

function SectionTitleNumbered({ title, number }: SectionTitleNumberedProps) {
  return (
    <div className="flex items-baseline mb-6">
      {/* 左側大編號 */}
      <span className="text-4xl font-bold text-gray-300 mr-4">{number}</span>
      {/* 中間標題 */}
      <h2 className="text-2xl font-semibold text-gray-800">{title}</h2>
      {/* 右側虛線延伸 */}
      <div className="flex-1 ml-4 border-t border-dashed border-gray-300 mt-3"></div>
    </div>
  );
}

export default function WhatIDid() {
  const FLOW_ITEMS: FlowItem[] = [
    { icon: Eye, label: "Observing factory video data" },
    { icon: BarChart3, label: "Data Analysis with Python" },
    { icon: Database, label: "Data Visualization & Reporting" },
    { icon: TrendingUp, label: "Driving Faster Root Cause Insights" },
  ];

  return (
    <motion.section
      className="space-y-12"
      initial="hidden"
      animate="visible"
      variants={sectionVariants}
    >
      <SectionTitle title="What I Did" />

      {/* 01 Root Cause Analysis */}
      <motion.div variants={itemVariants} className="space-y-6">
        <SectionTitleNumbered
          number="01"
          title="Root Cause Analysis：Faster Insights for Supervisors"
        />
        <FlowStepper items={FLOW_ITEMS} />
        <div className="rounded-xl ">
          <p className="text-base leading-relaxed">
            During my internship, I conducted root cause analyses on more than
            <strong> 1,000 factory videos</strong> combined with production
            data. By recording and analyzing <strong>key metrics</strong>, I
            helped supervisors gain{" "}
            <strong>faster insight into production bottlenecks</strong> and line
            performance.
          </p>

          <p className="text-base leading-relaxed mt-4">
            To handle <strong>large-scale datasets</strong>, I frequently used
            <strong> Python (pandas)</strong> for analysis and
            <strong> Matplotlib</strong> for visualization. I produced root
            cause analysis reports that supported decision-making and{" "}
            <strong>sped up issue resolution</strong>.
          </p>
        </div>
      </motion.div>

      {/* 02 Streamlit Tool */}
      <motion.div variants={itemVariants} className="space-y-6">
        <SectionTitleNumbered
          number="02"
          title="Visualization Prototype：Testing Feasibility with Streamlit"
        />
        <div className="space-y-4">
          <InfoCard tag="Pain Point" tone="slate">
            The client needed a new production indicator but manager was uncertain whether it would be impactful or technically feasible.
          </InfoCard>
          <InfoCard tag="Solution" tone="amber">
            <div>
              <p className="font-semibold text-slate-800">
                Built a rapid prototype with Streamlit
              </p>
              <ul className="mt-2 list-inside list-disc space-y-1.5 text-slate-600">
                <li>
                  Enabled the system to automatically calculate the requested indicator from input data.
                </li>
                <li>Implemented visualization with chart elements to display results clearly.</li>
                <li>Designed a simple UI for easy testing of the concept.</li>
              </ul>
            </div>
          </InfoCard>
          <InfoCard tag="Outcome" tone="amber">
            <ul className="list-inside list-disc space-y-1.5 text-slate-600">
              <li>Enabled my manager to quickly grasp the indicator values generated by the prototype.</li>
              <li>Accelerated the evaluation process, reducing the time needed to assess effectiveness.</li>
              <li>Facilitated smoother communication with developers by bridging business needs and technical details.</li>
            </ul>
          </InfoCard>

          <RoleCard imageSrc="/gril_point.png" label="My Role">
            <p>– Implemented the core features with Streamlit.</p>
            <p>
              – Designed and built the UI to ensure usability for non-technical
              users.
            </p>
          </RoleCard>
        </div>
      </motion.div>

      {/* 03 Internal Tool */}
      <motion.div variants={itemVariants} className="space-y-6">
        <SectionTitleNumbered
          number="03"
          title="Validation Tool：Streamlining Model Evaluation for Data Scientists"
        />
        <EmpathyMap size="md" />
        <div className="mt-5 space-y-4">
          <InfoCard tag="Solution" tone="amber">
            <ul className="list-inside list-disc space-y-1.5">
              <li>Built an internal tool to streamline model validation workflows.</li>
              <li>Designed visualizations to present system outputs against reference data in a clear, comparable format.</li>
              <li>Integrated supporting contextual information  to give analysts a more complete view.</li>
            </ul>
          </InfoCard>
          <InfoCard tag="Outcome" tone="amber">
            <ul className="list-inside list-disc space-y-1.5">
              <li>Enabled data scientists to evaluate results more efficiently, cutting down manual work.</li>
              <li>Accelerated the process of identifying performance gaps and improvement opportunities.</li>
              <li>Improved clarity and communication between technical and non-technical stakeholders.</li>
              <li>Successfully adopted by the data team as part of their  validation workflow.</li>
            </ul>
          </InfoCard>
          <RoleCard imageSrc="/girl_read.png" label="My Role">
            <p>
              – Served as the primary developer and lead UI designer for the visualization tool.
            </p>
            <p>
              – Created prototypes to validate ideas and incorporated feedback into iterative improvements.
            </p>
          </RoleCard>
        </div>
      </motion.div>

      {/* 04 LLM Agent Prototype */}
      <motion.div variants={itemVariants} className="space-y-6">
        <SectionTitleNumbered
          number="04"
          title="LLM Agent Prototype：Automating Data Analysis Workflows"
        />
        <div className="space-y-4">
          <InfoCard tag="Objective" tone="slate">
            Test whether a minimum viable prototype leveraging LLMs could support industrial engineering analysis, by automating repetitive steps like data extraction, cleaning, and generating preliminary reports.
          </InfoCard>
          <InfoCard tag="Approach" tone="amber">
            <ul className="list-inside list-disc space-y-1.5">
              <li>Built a workflow MVP in Dify that automated data collection, preprocessing, and LLM-based reporting.</li>
              <li>Used prompt engineering to refine response quality and ensure analysis outputs were structured and useful.</li>
            </ul>
          </InfoCard>
          <InfoCard tag="Result" tone="amber">
            <ul className="list-inside list-disc space-y-1.5">
              <li>
                Delivered a functional MVP that automatically generated preliminary analysis reports.
              </li>
              <li>The prototype was reviewed internally by managers to evaluate feasibility, and also shared with clients as an early proof-of-concept, sparking discussions on future applications.</li>
            </ul>
          </InfoCard>
          <RoleCard imageSrc="/girl_type.png" label="My Role">
            <p>
              – Designed and implemented an MVP LLM-Agent workflow using Dify.
            </p>
            <p>
              – Developed data preprocessing scripts in Python to automate extraction and cleaning of raw data.
            </p>
          </RoleCard>
        </div>
      </motion.div>
    </motion.section>
  );
}
